#!/bin/bash

config=$1
source project.cfg

function buildDebug() {
    echo "Building $PROJECT_NAME in debug mode..."

    mkdir -p build/debug
    cd build/debug
    cmake ../.. -DCMAKE_BUILD_TYPE=Debug -DPROJECT_NAME=$PROJECT_NAME -DMUSTARD_DIR=$MUSTARD_PATH -DSDL2_DIR=$SDL2_PATH
    cd ../..
    cmake --build build/debug
}

function buildRelease() {
    echo "Building $PROJECT_NAME in release mode..."

    mkdir -p build/release
    cd build/release
    cmake ../.. -DCMAKE_BUILD_TYPE=Release -DPROJECT_NAME=$PROJECT_NAME -DMUSTARD_DIR=$MUSTARD_PATH -DSDL2_DIR=$SDL2_PATH
    cd ../..
    cmake --build build/release
}

function buildAssets() {
    echo "Building asset archive..."

    cd assets

    KEY_LENGTH=64
    ENCRYPTION_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $KEY_LENGTH | head -n 1)

    ../$MUSTARD_PATH/bin/Mustard-AssetCompiler ../dist/$PROJECT_NAME.dat $ENCRYPTION_KEY

cat <<EOL > "../src/addArchive.cpp"
//  Generated by Mustard Engine Build Script
//  *** DO NOT MODIFY ***
AB::fileSystem.addArchive("$PROJECT_NAME.dat", "$ENCRYPTION_KEY");
EOL

    cd ..
}

function buildDist() {
    echo "Building $PROJECT_NAME for distribution..."

    buildAssets

    mkdir -p build/dist
    cd build/dist
    cmake ../.. -DCMAKE_BUILD_TYPE=Dist -DPROJECT_NAME=$PROJECT_NAME -DMUSTARD_DIR=$MUSTARD_PATH -DSDL2_DIR=$SDL2_PATH
    cd ../..
    cmake --build build/dist
}

if [ "$config" == "debug" ]; then
    buildDebug
elif [ "$config" == "release" ]; then
    buildRelease
elif [ "$config" == "assets" ]; then
    buildAssets
elif [ "$config" == "dist" ]; then
    buildDist
elif [ "$config" == "all" ]; then
    buildDebug
    buildRelease
    buildDist
else
    echo usage: ./build.sh config
    echo
    echo Where config is one of:
    echo
    echo debug
    echo release
    echo assets
    echo dist
    echo all
    echo
fi

