#!/bin/bash

config=$1
source project.cfg

function buildDebug() {
    echo "Building $PROJECT_NAME in debug mode..."

    mkdir -p build/debug
    cd build/debug
    cmake ../.. -DCMAKE_BUILD_TYPE=Debug -DPROJECT_NAME=$PROJECT_NAME -DMUSTARD_DIR=$MUSTARD_PATH -DSDL2_DIR=$SDL2_PATH
    cd ../..
    cmake --build build/debug
}

function buildRelease() {
    echo "Building $PROJECT_NAME in release mode..."

    mkdir -p build/release
    cd build/release
    cmake ../.. -DCMAKE_BUILD_TYPE=Release -DPROJECT_NAME=$PROJECT_NAME -DMUSTARD_DIR=$MUSTARD_PATH -DSDL2_DIR=$SDL2_PATH
    cd ../..
    cmake --build build/release
}

function buildWebDebug() {
    if [[ -z "${EMCMAKE}" ]]; then
        source ~/emsdk/emsdk_env.sh
    fi

    echo "Building $PROJECT_NAME for web in debug mode...";

    mkdir -p build/web-debug
    cd build/web-debug
    emcmake cmake ../.. -DCMAKE_BUILD_TYPE=Debug -DPROJECT_NAME=$PROJECT_NAME -DMUSTARD_DIR=$MUSTARD_PATH -DSDL2_DIR=$SDL2_PATH -DEMSCRIPTEN=ON
    cd ../..
    cmake --build build/web-debug
    mv bin/web-debug/$PROJECT_NAME-Web-Debug.html bin/web-debug/index.html
}

function buildWebRelease() {
    if [[ -z "${EMCMAKE}" ]]; then
        source ~/emsdk/emsdk_env.sh
    fi

    echo "Building $PROJECT_NAME for web in release mode...";

    mkdir -p build/web-release
    cd build/web-release
    emcmake cmake ../.. -DCMAKE_BUILD_TYPE=Release -DPROJECT_NAME=$PROJECT_NAME -DMUSTARD_DIR=$MUSTARD_PATH -DSDL2_DIR=$SDL2_PATH -DEMSCRIPTEN=ON
    cd ../..
    cmake --build build/web-release
    mv bin/web-release/$PROJECT_NAME-Web-Release.html bin/web-release/index.html
}

function buildAssets() {
    echo "Building asset archive..."

    cd assets

    KEY_LENGTH=64
    ENCRYPTION_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $KEY_LENGTH | head -n 1)

    ../$MUSTARD_PATH/bin/Mustard-AssetCompiler ../dist/$PROJECT_NAME.dat $ENCRYPTION_KEY

cat <<EOL > "../src/addArchive.cpp"
//  Generated by Mustard Engine Build Script
//  *** DO NOT MODIFY ***
AB::fileSystem.addArchive("$PROJECT_NAME.dat", "$ENCRYPTION_KEY");
EOL

    cd ..
}

function buildDist() {
    echo "Building $PROJECT_NAME for distribution..."

    buildAssets

    mkdir -p build/dist
    cd build/dist
    cmake ../.. -DCMAKE_BUILD_TYPE=Dist -DPROJECT_NAME=$PROJECT_NAME -DMUSTARD_DIR=$MUSTARD_PATH -DSDL2_DIR=$SDL2_PATH
    cd ../..
    cmake --build build/dist
}

if [ "$config" == "debug" ]; then
    buildDebug
elif [ "$config" == "release" ]; then
    buildRelease
elif [ "$config" == "web-debug" ]; then
    buildWebDebug
elif [ "$config" == "web-release" ]; then
    buildWebRelease
elif [ "$config" == "assets" ]; then
    buildAssets
elif [ "$config" == "dist" ]; then
    buildDist
elif [ "$config" == "all" ]; then
    buildDebug
    buildRelease
    buildDist
    buildWebDebug
    buildWebRelease
else
    echo usage: ./build.sh config
    echo
    echo Where config is one of:
    echo
    echo debug
    echo release
    echo web-debug
    echo web-release
    echo assets
    echo dist
    echo all
    echo
fi

